### ISSUE TITLE
Error: Failed to update ref: HttpError: Update is not a fast forward

### ISSUE THREAD

**Issue by tmilar** [zofrex/mirror-branch#6]
Hi,

I've been trying to put this job to use but I'm always getting this error.

My goal is to push to a `master` branch, then, do a merge commit and push to `develop`, **without using force**. 

The config is as follows:

```yml
      - name: Mirror branch master -> develop
        # Attempt to merge changes to develop.
        id: mirror
        uses: zofrex/mirror-branch@v1
        with:
          target-branch: develop
          force: false
          token: ${{ secrets.GITHUB_TOKEN }}
```
